### DISCUSSION TITLE
How to ignore unrecognized flags?

### DISCUSSION THREAD

**Discussion by BatmanAoD** [carapace-sh/carapace-bin#2027] [Q&A] [answered]
I have a Go project that happens to use a build-tag in each of its test files, so running tests requires the `-tags` command-line option.

Carapace doesn't seem to recognize this option, and in fact it breaks completing any arguments that come after `-tags`; here's completion in nushell:

```
>  go test -tags unit -f
-fERR  unknown shorthand flag: -tags
```

And here it is in Bash:

```
> go test -tags unit -f
ERR (unknown shorthand flag: -tags)
```

I'm sure adding it wouldn't be too hard, but this seems like a more general problem: why does one unrecognized flag prevent autocompleting on the rest of the command? Is there a way to configure Carapace to ignore unrecognized flags?

**Comment by rsteube** [comment, marked as answer]
Setting the environment variable `CARAPACE_LENIENT=1` allows unknown flags globally to circumvent such issues.
There are some disadvantages to this however. Like how these are generally handled as bool flags.
So flag arguments like `go test -tags unit` might be better passed as `go test -tags=unit` if the command accepts it.

[Overlays](https://rsteube.github.io/carapace-bin/overlay.html) are intended as a (temporary) workaround for this and also provide a way to complete the unknown flag. 

```yaml 
name: go
commands:
  - name: test
    description: test packages
    flags:
      -tags=: a comma-separated list of build tags
    completion:
      flag:
        tags: ["$_tools.golang.BuildTags ||| $uniquelist(,)"]
```

The reason why unknown flags break completion is that it is impossible to determine if the argument following it is consumend by the flag or a positional.
