### DISCUSSION TITLE
zoxide custom alias

### DISCUSSION THREAD

**Discussion by robrecord** [carapace-sh/carapace-bin#2211] [Q&A]
hi there, in zoxide you can customize the command from `z` and `zi` to whatever letter you like (eg. `d` and `di`). if this is done, it's impossible to get completions using carapace. (edit: in fact i am finding it impossible to get completions using the default commands as well). how could this be resolved? thank you.

**Comment by rsteube** [comment]
Shell aliases should work, but here zoxide probably registers a shell function under a different name.
A [User Spec](https://rsteube.github.io/carapace-bin/spec/user.html) should work:
```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: zi
parsing: disabled
completion:
  positionalany: ["$carapace.bridge.CarapaceBin([zoxide])"]
```
