### DISCUSSION TITLE
How to remove a subcommand from a built-in completor?

### DISCUSSION THREAD

**Discussion by balthild** [carapace-sh/carapace-bin#2797] [Q&A]
Specifically, I want to remove https://github.com/carapace-sh/carapace-bin/blob/master/completers/brew_completer/cmd/instal.go

I tried adding an overlay with `hidden` and it doesn't work:

```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: brew
commands:
  - name: instal
    hidden: true
```
