### DISCUSSION TITLE
How to use environment variables in macro arguments?

### DISCUSSION THREAD

**Discussion by SuniRein** [carapace-sh/carapace-bin#2856] [Q&A] [answered]
I want to define a spec like:

```yaml
name: command
flags:
  --flag: The flag to complete
completion:
  flag:
    flag: ["$file ||| $chdir(~/.local/share/command)"]
```

But the `~/.local/share/command` is actually defined by environment `$MY_COMMAND_HOME`. I have tried `$chdir($(echo $MY_COMMAND_HOME))` and `$chdir($MY_COMMAND_HOME)` but failed.

Is there an easy way to solve it?

**Comment by rsteube** [comment, marked as answer]
Specs still have some rough edges so a couple of edge cases might not work.

This seems to be fine though:
```yaml
name: chdir
flags:
  --flag=: The flag to complete
completion:
  flag:
    flag: ["$files ||| $chdir(${HOME})"]
```

- `=` flag suffix to signal that it takes a value
- `$files` plural
- `${ENV_NAME}` curly braces so that it isn't mistaken as macro
