### ISSUE TITLE
mycmd: Custom spec from example doesn't work for me

### ISSUE THREAD

**Issue by hustcer** [carapace-sh/carapace-bin#2332]
### Current Behavior

I just tried the example from [Spec](https://carapace-sh.github.io/carapace-bin/spec.html#spec), however it doesn't work for me. 

### Expected Behavior

It should work as the asciinema casts

### Steps To Reproduce

1. $ cat ~/.config/carapace/specs/mycmd.yaml
```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: mycmd
description: my command
flags:
  --optarg?: optarg flag
  -r, --repeatable*: repeatable flag
  -v=: flag with value
persistentflags:
  --help: bool flag
completion:
  flag:
    optarg: ["one", "two\twith description", "three\twith style\tblue"]
    v: ["$files"]
commands:
- name: sub
  description: subcommand
  completion:
    positional:
      - ["$list(,)", "1", "2", "3"]
      - ["$directories"]
```
2. Run `source <(carapace _carapace)` in bash
3. Input `mycmd` in commandline and press `Tab`, however, nothing appears

### Version

1.0.0

### OS

- [ ] Linux
- [X] OSX
- [ ] Windows

### Shell

- [X] Bash
- [ ] Elvish
- [ ] Fish
- [X] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

### Anything else?

$ cat ~/.config/carapace/specs/git.yaml
```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name:  git
description: the stupid content tracker
parsing: disabled
completion:
  positionalany: ["$carapace.bridge.Fish([git])"]
```
The git completion works for me in bash
