### ISSUE TITLE
<command> completer

### ISSUE THREAD

**Issue by avi-cenna** [carapace-sh/carapace-bin#2582]
### Command

./gradlew

### Description

./gradlew is the Gradle wrapper command. It is typically preferred by Kotlin developers over `gradle` because the wrapper ensures that everyone is using the same gradle version.

### Homepage

https://docs.gradle.org/current/userguide/gradle_wrapper.html

### Documentation

https://docs.gradle.org/current/userguide/gradle_wrapper.html

### Complexity

M

### Anything else?

I think we could reuse a lot of what's been done for the `gradle` completer. Please let me know if this is a sensible request, and I might be able to take a crack at implementing this.

**Comment by rsteube** [comment]
Hmm... don't think completion for binaries called with relative path (not using `PATH`) can be registered.
I'd say there should be a way for this, but probably needs some minor trickery (and likely a command in `PATH`).

For the moment something in the sense of this should be possible:
```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: gradlew
run: "$(./gradlew $@)"
parsing: disabled
completion:
  positionalany: ["$carapace.bridge.CarapaceBin([gradle])"]
```

Or with a custom shell script/command named `gradlew` in `PATH`:
```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: gradlew
run: "[gradle]"
```

But these still use the `gradle` command for completion of tasks at the moment.
