### ISSUE TITLE
Error with ls when aliased to eza

### ISSUE THREAD

**Issue by mathomp4** [carapace-sh/carapace-bin#2601]
### Current Behavior

I freely admit this is probably due to my setup, but I'm not sure what is happening and if I can fix it.

When I try and do tab completion with `ls` I get:

```
❯ ls
invalid argument "all" for "--color-scale" flag: strconv.ParseBool: parsing "all": invalid syntax
```

I can confirm carapace is doing this because if I comment out the:
```zsh
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
zstyle ':completion:*:git:*' group-order 'main commands' 'alias commands' 'external commands'
source <(carapace _carapace)
```
bits of my `.zshrc`, it doesn't throw the error.

Now for the the exciting bits. My `ls` is not `ls`. My `ls` is:
```zsh
COMMON_EZA_OPTIONS='--classify --icons --color=automatic --color-scale=all --header --group'
alias ls="eza $COMMON_EZA_OPTIONS --grid"
```
and if I turn that off, tab completion also works.

So, I guess my question is: Is there a way I can tell carapace that my `ls` is actually `eza`?

### Expected Behavior

I guess have carapace know that my `ls` is actually `eza`.

### Steps To Reproduce

This is how my system is setup:

1. Set up carapace in zshrc with:
```
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
zstyle ':completion:*:git:*' group-order 'main commands' 'alias commands' 'external commands'
source <(carapace _carapace)
```
2. Set EZA up with:
```
COMMON_EZA_OPTIONS='--classify --icons --color=automatic --color-scale=all --header --group'
alias ls="eza $COMMON_EZA_OPTIONS --grid"
```
3. Try doing `ls <tab>` 

### Version

develop (brew says 1.0.7)

### OS

- [X] Darwin
- [ ] Linux
- [ ] Termux
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [X] Zsh

## Polar

<a href="https://polar.sh/carapace-sh/carapace-bin/issues/2601">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2601/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-bin/issues/2601/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
Yes, I'm using eza as well:

1. use carapace to create an [alias](https://carapace-sh.github.io/carapace-bin/spec/run.html#alias) instead of your shell
```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: ls
run: "[eza]"
```

2. or [bridge](https://carapace-sh.github.io/carapace-bin/spec/bridge.html#carapacebin) the completion
```yaml
# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: ls
parsing: disabled
completion:
  positionalany: ["$carapace.bridge.CarapaceBin([eza])"]
```

**Comment by rsteube** [comment]
btw. this should also work (and be preferred as it let's carapace know the flags are already set):
```yaml
yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: ls
run: "[eza, --classify, --icons, --color=automatic, --color-scale=all, --header, --group]"
```

It's just that it seems the `--color-scale` flag is currently wrong in carapace - gotta fix that.
