### ISSUE TITLE
strange `_carapace` item when writring spec with nested commands

### ISSUE THREAD

**Issue by SuniRein** [carapace-sh/carapace-bin#2852]
### Current Behavior

When write a spce with nested commands, like

```yaml
name: nested
commands:
  - name: first
    commands:
      - name: second
```

A strange `_caparace` item appears when completing for `nested first`:

![Image](https://github.com/user-attachments/assets/a3e39161-e433-48b0-911a-efe9262255e0)

### Expected Behavior

Only `second` is expected.

### Steps To Reproduce

1. Create `nested.yaml` in `~/.config/carapace/specs`:
   ```yaml
   name: nested
   commands:
     - name: first
       commands:
         - name: second
   ```
2. Type `nested first ` and trigger completion.

### Version

1.3.3

### OS

- [ ] Darwin
- [x] Linux
- [ ] Termux
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [x] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [x] Zsh
